### ISSUE TITLE
Make all browser compatible

### ISSUE THREAD

**Issue by nelson-barnett** [The-Lammert-Lab/TinnitusExpWebApp.jl#14]
All work has been done on Chrome. Last checked, playing the audio does not work in Firefox. Never tested in Safari. Needs to be compatible with all three.

**Comment by panzii** [comment]
The audio works on my Firefox browser I also checked on Microsoft Edge and it works there too. We can test it further together and figure out why it doesn't work on your end. For now you could try and clear cache and data of your Firefox and see if it works.

This is the screen recording of this:
https://github.com/The-Lammert-Lab/TinnitusExpWebApp.jl/assets/58861810/dcf3d929-a547-4711-9552-ae5c377b6f69
