### ISSUE TITLE
table organization

### ISSUE THREAD

**Issue by nelson-barnett** [The-Lammert-Lab/TinnitusExpWebApp.jl#26]
Allow for table sorting by user. Also, move "Experiment Name" to top of admin view tables always.

**Comment by panzii** [comment]
Fixed the later part. Now "Experiment Name" is the first field in admin view table.

**Comment by panzii** [comment]
Added table sorting feature on the middle table. created a [branch](https://github.com/The-Lammert-Lab/TinnitusExpWebApp.jl/tree/Issue%2326--table-organization) with these changes.
