### ISSUE TITLE
Allow for AX experiments

### ISSUE THREAD

**Issue by nelson-barnett** [The-Lammert-Lab/TinnitusExpWebApp.jl#70]
Add support for building and running experiments with a target sound.

**Comment by nelson-barnett** [comment]
DETAILS: 

Currently, experiments are made of a stimulus generation algorithm "stimgen_type" and its settings. This is good for running patients who have tinnitus, where they can reference their own tinnitus when determining whether to answer yes/no to a stimulus. For lots of validation reasons, we want to make this is functional with people who do not have tinnitus. They need a "target sound" against which to compare each stimulus, the same way someone with the condition does. The way we implement this in practice is to play the same "target sound" before every stimulus.

What needs to be done:
- Every `Experiment` needs to hold a "target_sound" parameter.
- The "target_sound" field should either be null/empty or a simple name that references one of the files in [tinnitus-reconstruction/code/experiment/ATA/](https://github.com/The-Lammert-Lab/tinnitus-reconstruction/tree/fa24387c595219a5d18f911dd28911b93c75f0c3/code/experiment/ATA). For example, "Tinnitus_Buzzing_Tone_1sec.wav" would just be referred to as "Buzzing". 
- The option for this choice should be available when creating a new `Experiment` in the browser. Since the options won't change, this should be a preset list.
- Those target sounds need to be available to the website code.
- If an `Experiment` has a target sound, that sound must be played before every stimulus (separated by a small pause) during the protocol. 
    - The small pause is 300ms in the matlab version, which works pretty well. See [here](https://github.com/The-Lammert-Lab/tinnitus-reconstruction/blob/fa24387c595219a5d18f911dd28911b93c75f0c3/code/experiment/Protocols/RevCorr.m#L238).

I think that's it.

**Comment by panzii** [comment]
what should the UI look like to create AX experiment. Should we just add a field to the like this?
![targetUI](https://github.com/The-Lammert-Lab/TinnitusExpWebApp.jl/assets/58861810/06921703-da34-4ab6-a907-3336f837c9f5)
and how do we differentiate the normal Experiment which is currently supported from the AX experiments while creating the experiment?

**Comment by nelson-barnett** [comment]
Yes, just a field like that is exactly what I was thinking. I figured it could be left empty if it was a "regular" experiment. Otherwise maybe a button to toggle on/off the target sound field? Which do you think would feel better?

**Comment by panzii** [comment]
I think the latter one seems a good option with the toggle.

**Comment by panzii** [comment]
current update:
1. Added a toggle switch to determine if the new experiment is AX or not
2. Target Sound Input field appears when the toggle is switched on and disappears when switched off.
3. Create a new column in Experiments table, "target_sound", to store which target sound is associated with that AX experiment.
![image](https://github.com/The-Lammert-Lab/TinnitusExpWebApp.jl/assets/58861810/72dbe44f-9d8c-4bcc-b8a7-c8d2c7d1743c)

**Comment by nelson-barnett** [comment]
Good stuff!

Regarding the duration of the stimuli, every stimulus generation type in TinnitusReconstructor.jl has a `duration` field. I believe that is currently present when making an Experiment on the website. So, nothing needs to change there. One thing I did notice, which I can change, is that there's no validation for the duration field. Meaning someone could put in -5 seconds. That should be checked in TinnitusReconstructor.jl. 

For the target sound, maybe just add a `target_duration` field to Experiment and have that be presented as an option when making one on the website. The value can default to the `duration` value of the stimulus generation struct. It should be validated against `0 < target_duration <= 1`.

**Comment by panzii** [comment]
AX experiments now run as expected along with non-AX experiments in this [branch](https://github.com/The-Lammert-Lab/TinnitusExpWebApp.jl/tree/70-AX-Experiments)
